### ISSUE TITLE
mis-matched row names issue

### ISSUE THREAD

**Issue by klg-2016** [kaitlyngaynor/gorongosa-mesocarnivores#103]
https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/blob/d8fabe9d1e884e02efc94fd1eacfb218b6e99363/scripts/multi-season%20model/01-multi-season-data-prep.R#L62

Trying to create the 2016 detection history yields this error:
recordTable was converted from tibble to data.frame
Error in detectionHistory(recordTable = record_table_subset_16, camOp = camop_subset_16,  : 
  Not all values of stationCol in recordTable are matched by rownames of camOp

I think this is coming from how I removed rows(cameras) that were inoperable in 2017 and the camera names not matching, I need to figure out if that's correct/how to fix it

**Comment by kaitlyngaynor** [comment]
I'm not getting an error here. Is this still an issue for you?

**Comment by klg-2016** [comment]
No, I think I got it to work! I don't remember which lines did it but I got
it. I just forgot to close the issue--sorry!
