### ISSUE TITLE
how to get the same cameras for each season?

### ISSUE THREAD

**Issue by klg-2016** [kaitlyngaynor/gorongosa-mesocarnivores#104]
https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/blob/d8fabe9d1e884e02efc94fd1eacfb218b6e99363/scripts/multi-season%20model/01-multi-season-data-prep.R#L36

this is a SUPER messy/bad way to get the cameras to be the same, which is leading to issues with creating the detection history. There's got to be a better way to do this, right?

**Comment by kaitlyngaynor** [comment]
Yes, there's a better way! I have changed the way that this filtering was done (using dplyr::filter rather than base R subsetting). See commit here: https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/commit/f7e1d4de40bdbca2e08cd9b0677f2986f2f0c394
