### ISSUE TITLE
messy way of removing inoperable cameras

### ISSUE THREAD

**Issue by klg-2016** [kaitlyngaynor/gorongosa-mesocarnivores#105]
https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/blob/35f0b2dc915a5bb44f97bf93f6257186242a2dec/scripts/multi-season%20model/01-multi-season-data-prep.R#L56

`filter(!Camera %in% c("A06", "B05", "D09", "E12", "F09", "G10", "G12", "H09", "H11", "H13", "I14","J09","L09","L13","M08"))`

So this is also a really messy way of addressing this issue, and I'm concerned that it will continue to be an issue throughout other seasons as well. but I think it's necessary (we need to include the same cameras across seasons, right?) and I can't think of a logical filter to use for 2016 data because the restriction is based on 2017 cameras not operating.

**Comment by kaitlyngaynor** [comment]
Actually, another way to this would be `filter(Camera %in% rownames(camop_subset_17))`. Then it will filter to only cameras that are in the 2017 subset. I didn't make this change on my end, but you can do it on yours!

**Comment by kaitlyngaynor** [comment]
But... DO we need to include the same cameras across seasons? I don't necessarily know that we would have to, but maybe. I'm still new to this model of course

**Comment by klg-2016** [comment]
Oh! That's a good point. I thought we did, because if we're looking at something that we're thinking changes over time, I thought we'd need to hold the sites where we're investigating it constant.

**Comment by kaitlyngaynor** [comment]
Hmm but in theory, aren't we both modeling a) where species occur and b) how they change over time, so the one-season cameras could be used for the a) part but not the b)? Again, you know more than I do at this point. My instinct would be to try and run it and see if it throws an error. Maybe it will

**Comment by klg-2016** [comment]
Just implemented your better way of filtering, still going to check on the need for consistent sites across seasons

**Comment by klg-2016** [comment]
Based on our conversation with Kendall, I'm going to work with the idea that we should be using consistent sites across seasons. Let me know if you disagree.
