### ISSUE TITLE
issues with creating the camera operation matrix with the 2016-2019 data

### ISSUE THREAD

**Issue by klg-2016** [kaitlyngaynor/gorongosa-mesocarnivores#111]
https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/blob/f458aba3a7a198db1cd53bd63bca3b612ee5d5a1/scripts/multi-season%20model/01-multi-season-data-prep.R#L26

I'm starting to switch to the new spreadsheets that Meredith just shared and ran into an issue creating the camera operation matrix with the new data. That spreadsheet ("Camera_operation_year1-4") has more than one set of start/end dates for some of the cameras, as makes sense given it covers multiple seasons. However, the cameraOperation function doesn't like that and throws this error: "Error: 48 stations have more than 1 item in CTtable. Please specify 'cameraCol' or 'sessionCol'"

My first thought for how to address this was to call the times between active monitoring for cameras "problems" and rearrange the spreadsheet so that each station only has a single row. Do you think that might work? I'm not sure if I'm missing something basic for how the function is operating that would suggest no.

I also started looking into the issue in the camtrapR package description online (https://cran.r-project.org/web/packages/camtrapR/camtrapR.pdf) and found that you sessionCol is a variable accepted by cameraOperation, which is specifically for multi-season work so it seems like a better bet. It looks like you just create a "session" column in your data frame and fill it with the year (i.e. 2016). That should be mostly straightforward, except for not having a 1:1 relationship for the camera info and seasons (there are some active camera periods that include more than a single late dry period). For that, I'm thinking I might just try repeating the row so that every camera has a row for every season, with some duplicates. I'm close to winding down for the evening; this is the route I'm planning to pursue when I get back to work. Whenever you get a chance, I'd appreciate your thoughts! Thank you

**Comment by kaitlyngaynor** [comment]
I already raised this issue with Meredith & am waiting for her reply! I'm
going to make a consolidated version with one row per camera and will send
it to you once it's ready

**Comment by klg-2016** [comment]
Sounds good, thank you!

Do you have any sense of whether I'm "supposed" to use a sessionCol for
multi season work? My initial multi season thinking only included two
seasons and I didn't use that column; I did everything manually instead. It
looks like there's a way to do multi season detection histories, for
example, without doing it season by season like you helped me make a
function for though. So I'm not sure.

**Comment by kaitlyngaynor** [comment]
I don't think it matters much, either way, as long as it is in the right
format for unmarked. I guess sessionCol just helps you get there faster?

**Comment by klg-2016** [comment]
Okay! I'll keep working at it and let you know if I figure out anything
differently.

**Comment by klg-2016** [comment]
Currently using the data with one camera per row, will adjust if necessary. Closing this issue for now.
