### ISSUE TITLE
color for occupancy figures

### ISSUE THREAD

**Issue by klg-2016** [kaitlyngaynor/gorongosa-mesocarnivores#133]
https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/blob/28f3e622bf27cb972a889a9e6cc460e08629cd24/scripts/species-interaction-model/02-multi-species-occupancy-analysis-GNP.Rmd#L248

this is where the code for the occupancy figures for each spp starts, so where the change for color of the CIs would be implemented
If you're good to make that change, I'd appreciate it and will take a look after to see how you did it!

**Comment by kaitlyngaynor** [comment]
Git is being finnicky at the conference center so it's hard for me to pull & push but here's the fix, I think (I only changed the second line). Play around with the alpha value til it looks nice :) 

Also, maybe pick a blue that is less pure BLUE. If you just google "Color palette generators" you can probably find a nice quartet of hex codes to use for the four species. Then just replace both instances of "blue" with "#187bcd" (a blue I just found quickly) and there you have it.

```
civet_lake <- ggplot(data = civet_urema_predict, aes(x = urema_unscaled, y = Predicted)) +
    geom_ribbon(aes(ymin = lower, ymax = upper), fill = "blue", alpha = 0.75) +
    geom_line(colour = "blue") +
    ylim(0,1) +
    theme_bw() +
    labs(x = "Distance to Lake (km)") +
    ggtitle("Civet")
```

**Comment by kaitlyngaynor** [comment]
k hopefully it works! lmk if you have other questions

**Comment by klg-2016** [comment]
This isn't a question, but I *think* your suggested edit for creating plots with detection probabilities instead of occupancy probabilities worked. I haven't implemented your code for the color yet. 
![image](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/assets/66888714/7e625683-e290-4403-a1d9-ed2ed7560702)

**Comment by klg-2016** [comment]
and the color code works too! 
![image](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/assets/66888714/7619dbb4-1ea1-44f4-9117-31e9c8076c13)
I'm going to keep the four main colors I have for now, because I'm not 100% sure where the code is for the temporal overlap figure and if I run out of time to find it, I want to have the colors be the same as they were in my thesis.

**Comment by kaitlyngaynor** [comment]
Great! You might play around with the y-axis scale too—could bound between 0 and 0.5, for example, if detection probabilities are low

**Comment by kaitlyngaynor** [comment]
I think the temporal overlap figure is line 141 here? https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/blob/master/scripts/temporal-analysis/01-temporal-overlap-calculation.R

**Comment by klg-2016** [comment]
huh, what a concept looking in the script labeled 01-temporal-overlap-calculation (for whatever reason, my brain/eyes could not find/see that script). that looks like it, thank you!

**Comment by klg-2016** [comment]
![image](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/assets/66888714/d993a9e9-2129-4462-af96-c9320285be15)

**Comment by kaitlyngaynor** [comment]
Looking good! You might actually change the y-axes so they vary by species, since overall detection probs are lower for honey badger & marsh mongoose... I could see using 0-0.20 for civet, 0-0.25 for genet, and 0-0.05 or 0.10 for honey badger and marsh mongoose? what do you think? I don't think it's necessarily misleading, particularly if you add a statement to the caption that says something like "We varied the y-axis scale by species for legibility, given differences in detection probabilities across species."

**Comment by klg-2016** [comment]
yeah I was thinking leave it consistent to not be misleading, but you're right that it's harder to see the relationship for hb/mm with this axis. I'll edit and see what we think

**Comment by klg-2016** [comment]
![image](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/assets/66888714/406aea59-401c-42d6-bc38-51f827cfc702)
![image](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/assets/66888714/7e8a2ea0-3853-448e-bc0c-0767dc597275)
also edited colors on the temporal figure, thank you again for pointing me in the right direction

**Comment by kaitlyngaynor** [comment]
I like it! I think it's ok especially because the lines for HB & MM are _still_ lower than the line for genet. If they were above that line, I think that's when it would start to look misleading.

If I may continue to be nit-picky, I'd increase the line width on the temporal figures - it's kind of hard to see honey badger. I think you'd have to change it in the original function you wrote here, though (lwd = 3 or something):

https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/blob/9408910fb3bd3c3b14c10d513a643b1b1ae9dbbe/scripts/temporal-analysis/02-temporal-figure-functions.R#L354-L357

**Comment by kaitlyngaynor** [comment]
To clarify one more thing—didn't you go with # of termite mounds (in 1km) rather than termite mound density?

**Comment by klg-2016** [comment]
Yes, it is number of termite mounds - in my thesis, we also used number of termite mounds and I still labeled it "Density", which writing out now doesn't actually make sense. I'll edit to "Number of termite mounds" (or "Number of termite mounds in a 1km radius"? or "Termite mounds in a 1km radius"?) 
Will also work on thickening lines
(please be nitpicky, if I can get these figures so they're basically ready to go today/early this week, that's going to be super helpful when it comes time to submit)

**Comment by klg-2016** [comment]
there's the thicker lines:
![image](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/assets/66888714/9021653f-5124-4879-9571-88e4d1446555)

**Comment by klg-2016** [comment]
and edited labels:
![image](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/assets/66888714/96ddc402-bdc7-43a9-9b58-85b66fc2df7a)

**Comment by klg-2016** [comment]
![image](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/assets/66888714/9c8d0b90-c1d5-4846-a699-b1cf6e47e2bb)
![image](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/assets/66888714/35cfe78b-7b83-4d10-9d1b-d1126b018393)

I think thicker is easier to see. The temporal figure now looks like a little kid scribbled with crayon (but not in a bad way, it just makes me smile)

**Comment by kaitlyngaynor** [comment]
ok last nit-picky comment (hopefully) -- can you make the line width in the detection prob plots thicker too, for consistency (and ease of seeing the line)?

**Comment by kaitlyngaynor** [comment]
I probably shouldn't promise that, there may be more... anyway you can do that with size = 2 or size = 3 in the aes() argument of geom_line()

**Comment by klg-2016** [comment]
![image](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/assets/66888714/688dfec9-824e-41c7-9dc2-e53e98624166)

this is linewidth = 1 (size = was deprecated), actually, because 2 looked too thick. what do you think?

**Comment by klg-2016** [comment]
I'm thinking it may also be too thick

**Comment by kaitlyngaynor** [comment]
I actually like it, plus it better matches the temporal graph. I find 1 pt lines too thin... it's a matter of personal preference of course

**Comment by kaitlyngaynor** [comment]
I should have given you all of my comments at once, but I think you want "Predicted" to read "Detection Probability"

**Comment by klg-2016** [comment]
![image](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/assets/66888714/b7e6f447-e483-4b37-82f0-62e4d5e249e2)

I think the only thing that's getting me with the line thickness is where it's almost as thick as the confidence interval, but I don't think that's ever actually true so I think it works.

**Comment by klg-2016** [comment]
justed edited lion axis to read "Relative Lion Activity"
