### ISSUE TITLE
occupancy for four focal spp

### ISSUE THREAD

**Issue by klg-2016** [kaitlyngaynor/gorongosa-mesocarnivores#134]
https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/blob/18379451c8ee89be56b6d25b222e82fe37c2e101/scripts/full-guild-model/01-generate-model-input.R#L7

I'm running through some of my to dos for this manuscript, and one of those is pulling the occupancy estimates for marsh mongoose and honey badger (it's already in my thesis for civets and genets as they had the highest occupancy, and I have the other two on a graph but no number estimates and CIs). 

Looking through this code, I'm not sure I ever actually ran some of it. For both this script and the 02-occupancy-model-Rich.Rmd, I don't have some of the starting files to work with on my laptop. It looks like the 02 script generates csvs with the occupancy estimates, so you may have them saved on your laptop already and not need to rerun anything. When you get a chance, could you please check that out? I'll tag what looks like the general area in that script below. 

Thank you!

**Comment by klg-2016** [comment]
Okay I'm not sure how to put something from another script in this issue, but it looks like the section that starts on line 120 (### Occupancy and detection probabilities) in "02-occupancy-model-Rich.Rmd" under "full-guild-model" has the information I need for the other two species.

**Comment by kaitlyngaynor** [comment]
Here’s the file that is read in on in that line you linked, plus what I think was spit out when run with the arguments on line 93—let me know if there are other specific files that you need me to track down!

[camoperation-dry2016_katie-8_1_16-11_30_16.csv](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/files/12262885/camoperation-dry2016_katie-8_1_16-11_30_16.csv)
[detections-dry2016_katie-8_1_16-11_30_16.csv](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/files/12262886/detections-dry2016_katie-8_1_16-11_30_16.csv)
[All_species_by_date_year1and2_082919.csv](https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/files/12262894/All_species_by_date_year1and2_082919.csv)

**Comment by kaitlyngaynor** [comment]
Re: your second comment, I don't think you want to use the occupancy probabilities from the full guild model—I'd report them for the model you actually ran!

**Comment by klg-2016** [comment]
this may be a really dumb question, but where in the interaction model does it give occupancy probabilities? For the top model (whatever we land on), it gives an occupancy intercept, but that's not the same thing, is it? it doesn't go 0-1.

**Comment by kaitlyngaynor** [comment]
not a dumb question at all... I think the Bayesian model calculated mean occupancy probability (based on model predictions), and I'm not sure if the Rota model does this along the way. 

One option is to just present "naive occupancy" which is really simply = # of camera sites detected / total # camera sites. This is easiest and most straightforward.

Another option (not mutually exclusive) is to look into papers that use the Rota model, and see what results they report in their papers.

**Comment by klg-2016** [comment]
Okay! You'd already suggested calculating "naive occupancy", so I may start there and then can also look into other papers.

**Comment by klg-2016** [comment]
I added naive occupancy to the draft. Parsons et al (2019) uses the Rota model (and Rota is a co-author), and they report only detection rates with standard error for each of their different habitat types (i.e. urban, suburban, etc). 
I calculated detection rates by taking number of detections/number of trap days, I'm not sure how to get the standard error (we'd need more detections/day numbers, do you think they found the number of detections/day for every camera and then averaged and found the SE that way?) If so, I need to remember how to find number of detections for a given spp at a given camera .

**Comment by kaitlyngaynor** [comment]
Good approach. To clarify, did you calculate overall detection rates (total detections / total trap-nights) or mean detection rate (across cameras)? I could see the value in reporting both, but not sure how necessary it is at this point. I'm assuming you did the former if you don't have detections/day for each camera.

And yes I presume they calculated SE across sites as you suggest.

**Comment by klg-2016** [comment]
You're correct, I did the former - total detections for a species/total trap-nights

**Comment by klg-2016** [comment]
adding this link here because I think it tells you how to find marginal occupancy using this model, if we decide we want it:
https://cran.r-project.org/web/packages/unmarked/vignettes/occuMulti.html#plotting-marginal-occupancy

**Comment by klg-2016** [comment]
I don't think I need any thoughts here (we landed on naive occupancy, which I think is fine), and I'll take a look at issues below. Some are from a while back and related to multi-season or Kellner model work
