### ISSUE TITLE
questions for publication scripts

### ISSUE THREAD

**Issue by klg-2016** [kaitlyngaynor/gorongosa-mesocarnivores#139]
I'm working on prepping the data and scripts for publication, and I'm going to keep my questions together here
- should I include an annotation about the warning that comes up when I create a data object for the models? it's the one we discussed where one of the species (genet) had had one fewer NA in its detection history. here is my full annotation for myself: #this line yields this warning: In unmarkedFrameOccuMulti(y = y, siteCovs = occ_covs, obsCovs = det_covs): Missing obs do not match among species. Converting some obs to NAs so they match.
#I think this means that the location of the NAs is not the same across all species, but I have no idea why that would be the case
#there are 459 NAs in civet, mm, and hb detection histories, and 458 in genet
#not sure where/why the difference is, but also not *too* worried about it?
#the warning suggests they just added an NA wherever that "extra" observation was

this is ~line 54 of 01-multi-species-occupancy-analysis-pub.Rmd

**Comment by klg-2016** [comment]
I have some things named with "_23" at the end to distinguish, is that okay?

**Comment by klg-2016** [comment]
second update: I believe the code and the data are all edited for publication. I have "-pub" in some of my script names to clarify which is which. I can send you the simplified .csv data files if you want to run anything, or if you wouldn't mind just taking a look and making sure formatting looks okay. I reran everything except the bootstrapping for the temporal analysis because that takes a long time, but basically nothing changed in that script so it should be fine

**Comment by kaitlyngaynor** [comment]
> * should I include an annotation about the warning that comes up when I create a data object for the models? it's the one we discussed where one of the species (genet) had had one fewer NA in its detection history. here is my full annotation for myself: #this line yields this warning: In unmarkedFrameOccuMulti(y = y, siteCovs = occ_covs, obsCovs = det_covs): Missing obs do not match among species. Converting some obs to NAs so they match.
>   #I think this means that the location of the NAs is not the same across all species, but I have no idea why that would be the case
>   #there are 459 NAs in civet, mm, and hb detection histories, and 458 in genet
>   #not sure where/why the difference is, but also not _too_ worried about it?
>   #the warning suggests they just added an NA wherever that "extra" observation was
> 
> this is ~line 54 of 01-multi-species-occupancy-analysis-pub.Rmd

probably fine to exclude?


> I have some things named with "_23" at the end to distinguish, is that okay? update: I simplified things like occFormulas6_23, but currently still have things with _23

probably fine—I usually like to clean this kind of stuff up just to reduce confusion but not necessary

-pub is fine in script names
