### ISSUE TITLE
why are the labels wonky?

### ISSUE THREAD

**Issue by klg-2016** [kaitlyngaynor/gorongosa-mesocarnivores#86]
https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/blob/25e06a4f54eb499f9093bc5a09b8ab3cd7f0b0a3/scripts/02-multi-species-occupancy-analysis-GNP.Rmd#L317

This line of code now produces this figure:
![image](https://user-images.githubusercontent.com/66888714/92274372-19f4f380-eebb-11ea-9dc6-46fa1489b2a6.png)

Two questions:
- I know color choice is a preference thing, but do these look alright?
- Any insight into why the species name labels are in weird/not consistent places for each plot?

**Comment by kaitlyngaynor** [comment]
Closing this since it seems to be sorted out.... feel free to reopen if you disagree of course
