### ISSUE TITLE
project directory/location?

### ISSUE THREAD

**Issue by klg-2016** [kaitlyngaynor/gorongosa-mesocarnivores#94]
I just made the switch from my Oxford OneDrive account to my McGill OneDrive account and I'm trying to move this project over. On my computer, I copied my whole thesis folder (including the modeling files) into the McGill OneDrive. Through RStudio, I switched my working directory to the new OneDrive, and then made a new script for the Serengeti data prep in that folder.  With that new script, no option came up to commit it to GitHub and when I go to the project directory for this project, it's still in the Oxford OneDrive account. Any thoughts on how to address this? Do you know if I need to re-download the project itself in the new OneDrive?

**Comment by kaitlyngaynor** [comment]
Hmm, you have opened the RProj file and definitely have the project open?
The invisible git file should live in the same folder as that file. And you
shouldn't need to set working directories when you use RProjects (it just
automatically treats the folder with the RProj file as your working
directory)

I'm afraid I can't troubleshoot beyond that but I advise you to just Google
stuff about git and RStudio and moving folders!

**Comment by klg-2016** [comment]
I fixed it! I deleted the gorongosa-mesocarnivores folder from my Ox storage, and reopened the project from the McGill storage and that worked. Thank you!
