### ISSUE TITLE
error when downloading

### ISSUE THREAD

**Issue by klg-2016** [kaitlyngaynor/gorongosa-mesocarnivores#97]
https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/blob/953362c116b6fdf9b3754da40a44dbd4c48ef0b9/Image%20ID/download-images-from-url.R#L40

Just noting this here. 
when I try to run this code, the following error comes up:
Error in charToRaw(URL) : argument must be a character vector of length 1.

Not sure why, so switching to using the links following Kaitlyn's advice

**Comment by kaitlyngaynor** [comment]
Closing this issue since we've found a workaround
